version: '3.9'
services:
  cng-reload:
    build: .
    ports:
      - 3000:3000
    networks:
      - cng-reload
  prom:
    image: prom/prometheus:v2.23.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cng-reload
networks:
  cng-reload:
